require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.nvimtree"
require "user.indent"
require "user.telescope"
require "user.cmp"
vim.cmd "colorscheme onedark" 
--require "user.lsp"
require("lualine").setup()
